// Code generated by protoc-gen-go. DO NOT EDIT.
// source: member.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisteyReq struct {
	Version              *Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	MInfo                *Member  `protobuf:"bytes,2,opt,name=m_info,json=mInfo,proto3" json:"m_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisteyReq) Reset()         { *m = RegisteyReq{} }
func (m *RegisteyReq) String() string { return proto.CompactTextString(m) }
func (*RegisteyReq) ProtoMessage()    {}
func (*RegisteyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{0}
}

func (m *RegisteyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteyReq.Unmarshal(m, b)
}
func (m *RegisteyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteyReq.Marshal(b, m, deterministic)
}
func (m *RegisteyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteyReq.Merge(m, src)
}
func (m *RegisteyReq) XXX_Size() int {
	return xxx_messageInfo_RegisteyReq.Size(m)
}
func (m *RegisteyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteyReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteyReq proto.InternalMessageInfo

func (m *RegisteyReq) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *RegisteyReq) GetMInfo() *Member {
	if m != nil {
		return m.MInfo
	}
	return nil
}

type CreateReq struct {
	Version              *Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{1}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *CreateReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type DeleteReq struct {
	Version              *Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	MId                  int64    `protobuf:"varint,2,opt,name=m_id,json=mId,proto3" json:"m_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReq) Reset()         { *m = DeleteReq{} }
func (m *DeleteReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReq) ProtoMessage()    {}
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{2}
}

func (m *DeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq.Unmarshal(m, b)
}
func (m *DeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq.Marshal(b, m, deterministic)
}
func (m *DeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq.Merge(m, src)
}
func (m *DeleteReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReq.Size(m)
}
func (m *DeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq proto.InternalMessageInfo

func (m *DeleteReq) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *DeleteReq) GetMId() int64 {
	if m != nil {
		return m.MId
	}
	return 0
}

type ModityReq struct {
	Version              *Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	MId                  int64    `protobuf:"varint,2,opt,name=m_id,json=mId,proto3" json:"m_id,omitempty"`
	MInfo                *Member  `protobuf:"bytes,3,opt,name=m_info,json=mInfo,proto3" json:"m_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModityReq) Reset()         { *m = ModityReq{} }
func (m *ModityReq) String() string { return proto.CompactTextString(m) }
func (*ModityReq) ProtoMessage()    {}
func (*ModityReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{3}
}

func (m *ModityReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModityReq.Unmarshal(m, b)
}
func (m *ModityReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModityReq.Marshal(b, m, deterministic)
}
func (m *ModityReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModityReq.Merge(m, src)
}
func (m *ModityReq) XXX_Size() int {
	return xxx_messageInfo_ModityReq.Size(m)
}
func (m *ModityReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ModityReq.DiscardUnknown(m)
}

var xxx_messageInfo_ModityReq proto.InternalMessageInfo

func (m *ModityReq) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *ModityReq) GetMId() int64 {
	if m != nil {
		return m.MId
	}
	return 0
}

func (m *ModityReq) GetMInfo() *Member {
	if m != nil {
		return m.MInfo
	}
	return nil
}

type LoginReq struct {
	Version              *Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	MName                string   `protobuf:"bytes,2,opt,name=m_name,json=mName,proto3" json:"m_name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{4}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *LoginReq) GetMName() string {
	if m != nil {
		return m.MName
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{5}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type MemberInfoReq struct {
	Version              *Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	MName                string   `protobuf:"bytes,3,opt,name=m_name,json=mName,proto3" json:"m_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberInfoReq) Reset()         { *m = MemberInfoReq{} }
func (m *MemberInfoReq) String() string { return proto.CompactTextString(m) }
func (*MemberInfoReq) ProtoMessage()    {}
func (*MemberInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{6}
}

func (m *MemberInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberInfoReq.Unmarshal(m, b)
}
func (m *MemberInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberInfoReq.Marshal(b, m, deterministic)
}
func (m *MemberInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberInfoReq.Merge(m, src)
}
func (m *MemberInfoReq) XXX_Size() int {
	return xxx_messageInfo_MemberInfoReq.Size(m)
}
func (m *MemberInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_MemberInfoReq proto.InternalMessageInfo

func (m *MemberInfoReq) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *MemberInfoReq) GetMName() string {
	if m != nil {
		return m.MName
	}
	return ""
}

type MemberInfoResp struct {
	MName                string   `protobuf:"bytes,1,opt,name=m_name,json=mName,proto3" json:"m_name,omitempty"`
	IsSeller             bool     `protobuf:"varint,2,opt,name=is_seller,json=isSeller,proto3" json:"is_seller,omitempty"`
	Balanc               float64  `protobuf:"fixed64,3,opt,name=balanc,proto3" json:"balanc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberInfoResp) Reset()         { *m = MemberInfoResp{} }
func (m *MemberInfoResp) String() string { return proto.CompactTextString(m) }
func (*MemberInfoResp) ProtoMessage()    {}
func (*MemberInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{7}
}

func (m *MemberInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberInfoResp.Unmarshal(m, b)
}
func (m *MemberInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberInfoResp.Marshal(b, m, deterministic)
}
func (m *MemberInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberInfoResp.Merge(m, src)
}
func (m *MemberInfoResp) XXX_Size() int {
	return xxx_messageInfo_MemberInfoResp.Size(m)
}
func (m *MemberInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_MemberInfoResp proto.InternalMessageInfo

func (m *MemberInfoResp) GetMName() string {
	if m != nil {
		return m.MName
	}
	return ""
}

func (m *MemberInfoResp) GetIsSeller() bool {
	if m != nil {
		return m.IsSeller
	}
	return false
}

func (m *MemberInfoResp) GetBalanc() float64 {
	if m != nil {
		return m.Balanc
	}
	return 0
}

type MemberListReq struct {
	Version              *Version                `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Category             *MemberListReq_Category `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *MemberListReq) Reset()         { *m = MemberListReq{} }
func (m *MemberListReq) String() string { return proto.CompactTextString(m) }
func (*MemberListReq) ProtoMessage()    {}
func (*MemberListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{8}
}

func (m *MemberListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberListReq.Unmarshal(m, b)
}
func (m *MemberListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberListReq.Marshal(b, m, deterministic)
}
func (m *MemberListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberListReq.Merge(m, src)
}
func (m *MemberListReq) XXX_Size() int {
	return xxx_messageInfo_MemberListReq.Size(m)
}
func (m *MemberListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberListReq.DiscardUnknown(m)
}

var xxx_messageInfo_MemberListReq proto.InternalMessageInfo

func (m *MemberListReq) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *MemberListReq) GetCategory() *MemberListReq_Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type MemberListReq_Category struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	IsSeller             bool     `protobuf:"varint,2,opt,name=is_seller,json=isSeller,proto3" json:"is_seller,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberListReq_Category) Reset()         { *m = MemberListReq_Category{} }
func (m *MemberListReq_Category) String() string { return proto.CompactTextString(m) }
func (*MemberListReq_Category) ProtoMessage()    {}
func (*MemberListReq_Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{8, 0}
}

func (m *MemberListReq_Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberListReq_Category.Unmarshal(m, b)
}
func (m *MemberListReq_Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberListReq_Category.Marshal(b, m, deterministic)
}
func (m *MemberListReq_Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberListReq_Category.Merge(m, src)
}
func (m *MemberListReq_Category) XXX_Size() int {
	return xxx_messageInfo_MemberListReq_Category.Size(m)
}
func (m *MemberListReq_Category) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberListReq_Category.DiscardUnknown(m)
}

var xxx_messageInfo_MemberListReq_Category proto.InternalMessageInfo

func (m *MemberListReq_Category) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *MemberListReq_Category) GetIsSeller() bool {
	if m != nil {
		return m.IsSeller
	}
	return false
}

type MemberListResp struct {
	MList                []*MemberListResp_MemberList `protobuf:"bytes,1,rep,name=m_list,json=mList,proto3" json:"m_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *MemberListResp) Reset()         { *m = MemberListResp{} }
func (m *MemberListResp) String() string { return proto.CompactTextString(m) }
func (*MemberListResp) ProtoMessage()    {}
func (*MemberListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{9}
}

func (m *MemberListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberListResp.Unmarshal(m, b)
}
func (m *MemberListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberListResp.Marshal(b, m, deterministic)
}
func (m *MemberListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberListResp.Merge(m, src)
}
func (m *MemberListResp) XXX_Size() int {
	return xxx_messageInfo_MemberListResp.Size(m)
}
func (m *MemberListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberListResp.DiscardUnknown(m)
}

var xxx_messageInfo_MemberListResp proto.InternalMessageInfo

func (m *MemberListResp) GetMList() []*MemberListResp_MemberList {
	if m != nil {
		return m.MList
	}
	return nil
}

type MemberListResp_MemberList struct {
	MName                string   `protobuf:"bytes,1,opt,name=m_name,json=mName,proto3" json:"m_name,omitempty"`
	IsSeller             bool     `protobuf:"varint,2,opt,name=is_seller,json=isSeller,proto3" json:"is_seller,omitempty"`
	Balanc               float64  `protobuf:"fixed64,3,opt,name=balanc,proto3" json:"balanc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberListResp_MemberList) Reset()         { *m = MemberListResp_MemberList{} }
func (m *MemberListResp_MemberList) String() string { return proto.CompactTextString(m) }
func (*MemberListResp_MemberList) ProtoMessage()    {}
func (*MemberListResp_MemberList) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{9, 0}
}

func (m *MemberListResp_MemberList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberListResp_MemberList.Unmarshal(m, b)
}
func (m *MemberListResp_MemberList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberListResp_MemberList.Marshal(b, m, deterministic)
}
func (m *MemberListResp_MemberList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberListResp_MemberList.Merge(m, src)
}
func (m *MemberListResp_MemberList) XXX_Size() int {
	return xxx_messageInfo_MemberListResp_MemberList.Size(m)
}
func (m *MemberListResp_MemberList) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberListResp_MemberList.DiscardUnknown(m)
}

var xxx_messageInfo_MemberListResp_MemberList proto.InternalMessageInfo

func (m *MemberListResp_MemberList) GetMName() string {
	if m != nil {
		return m.MName
	}
	return ""
}

func (m *MemberListResp_MemberList) GetIsSeller() bool {
	if m != nil {
		return m.IsSeller
	}
	return false
}

func (m *MemberListResp_MemberList) GetBalanc() float64 {
	if m != nil {
		return m.Balanc
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisteyReq)(nil), "RegisteyReq")
	proto.RegisterType((*CreateReq)(nil), "CreateReq")
	proto.RegisterType((*DeleteReq)(nil), "DeleteReq")
	proto.RegisterType((*ModityReq)(nil), "ModityReq")
	proto.RegisterType((*LoginReq)(nil), "LoginReq")
	proto.RegisterType((*LoginResp)(nil), "LoginResp")
	proto.RegisterType((*MemberInfoReq)(nil), "MemberInfoReq")
	proto.RegisterType((*MemberInfoResp)(nil), "MemberInfoResp")
	proto.RegisterType((*MemberListReq)(nil), "MemberListReq")
	proto.RegisterType((*MemberListReq_Category)(nil), "MemberListReq.Category")
	proto.RegisterType((*MemberListResp)(nil), "MemberListResp")
	proto.RegisterType((*MemberListResp_MemberList)(nil), "MemberListResp.MemberList")
}

func init() { proto.RegisterFile("member.proto", fileDescriptor_9b9836b7e13de206) }

var fileDescriptor_9b9836b7e13de206 = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x55, 0xd6, 0xa6, 0x4b, 0x6e, 0xc7, 0x10, 0x16, 0x8c, 0x29, 0x93, 0x26, 0xf0, 0xd3, 0x1e,
	0xc0, 0x83, 0xee, 0x91, 0x07, 0xa4, 0x15, 0x1e, 0x86, 0x36, 0x24, 0x3c, 0x09, 0x21, 0x84, 0x54,
	0x25, 0xcd, 0x6d, 0x64, 0x11, 0xc7, 0x21, 0x0e, 0x43, 0xfd, 0x18, 0x3e, 0x80, 0x4f, 0xe1, 0xaf,
	0x50, 0xec, 0x38, 0x4d, 0x11, 0x54, 0x05, 0xed, 0xa9, 0x3d, 0xf1, 0xd1, 0xb9, 0xe7, 0x5e, 0xdf,
	0x63, 0xd8, 0x93, 0x28, 0x13, 0xac, 0x58, 0x59, 0xa9, 0x5a, 0x45, 0x63, 0xa9, 0x52, 0xcc, 0x5b,
	0x70, 0x94, 0x29, 0x95, 0xe5, 0x78, 0x6a, 0x50, 0xf2, 0x75, 0x71, 0x8a, 0xb2, 0xac, 0x97, 0xf6,
	0x90, 0xbe, 0x83, 0x31, 0xc7, 0x4c, 0xe8, 0x1a, 0x97, 0x1c, 0xbf, 0x10, 0x0a, 0xbb, 0x37, 0x58,
	0x69, 0xa1, 0x8a, 0x43, 0xef, 0x91, 0x77, 0x32, 0x9e, 0x04, 0xec, 0xbd, 0xc5, 0xdc, 0x1d, 0x90,
	0x63, 0x18, 0xc9, 0x99, 0x28, 0x16, 0xea, 0x70, 0xc7, 0x50, 0x76, 0xd9, 0x95, 0xa9, 0xcd, 0x7d,
	0x79, 0x51, 0x2c, 0x14, 0x9d, 0x42, 0x38, 0xad, 0x30, 0xae, 0x71, 0x5b, 0x41, 0x02, 0xc3, 0xb9,
	0x4a, 0xd1, 0xc8, 0x85, 0xdc, 0xfc, 0xa7, 0xe7, 0x10, 0xbe, 0xc2, 0x1c, 0xb7, 0x17, 0xb9, 0x07,
	0x43, 0x39, 0x13, 0xa9, 0x11, 0x19, 0xf0, 0x81, 0xbc, 0x48, 0x69, 0x02, 0xe1, 0x95, 0x4a, 0x45,
	0xbd, 0xfc, 0x7f, 0x8d, 0x5e, 0xb3, 0x83, 0x3f, 0x36, 0x1b, 0x43, 0x70, 0xa9, 0x32, 0x51, 0x6c,
	0x5b, 0xe2, 0x41, 0xa3, 0x57, 0xc4, 0xd2, 0x75, 0xeb, 0xcb, 0xb7, 0xb1, 0x44, 0x12, 0x41, 0x50,
	0xc6, 0x5a, 0x7f, 0x53, 0x55, 0x6a, 0x0a, 0x85, 0xbc, 0xc3, 0xf4, 0x31, 0x84, 0x6d, 0x09, 0x5d,
	0x92, 0xfb, 0xe0, 0xd7, 0xea, 0x33, 0xda, 0x0a, 0x21, 0xb7, 0x80, 0xbe, 0x81, 0x3b, 0xd6, 0x56,
	0xe3, 0xe9, 0xdf, 0xad, 0x0c, 0x7a, 0x56, 0xe8, 0x27, 0xd8, 0xef, 0x6b, 0xe9, 0xb2, 0x47, 0xf4,
	0xfa, 0x9e, 0x8f, 0x20, 0x14, 0x7a, 0xa6, 0x31, 0xcf, 0xb1, 0x32, 0xdd, 0x04, 0x3c, 0x10, 0xfa,
	0xda, 0x60, 0x72, 0x00, 0xa3, 0x24, 0xce, 0xe3, 0x62, 0x6e, 0xc4, 0x3d, 0xde, 0x22, 0xfa, 0xc3,
	0x73, 0x56, 0x2f, 0x85, 0xae, 0xb7, 0xb5, 0x7a, 0x06, 0xc1, 0x3c, 0xae, 0x31, 0x53, 0xd5, 0xb2,
	0x5d, 0xba, 0x87, 0x6c, 0x4d, 0x85, 0x4d, 0xdb, 0x63, 0xde, 0x11, 0xa3, 0x97, 0x10, 0xb8, 0xaf,
	0x8d, 0x1d, 0xb5, 0x58, 0x68, 0xac, 0x4d, 0x0d, 0x9f, 0xb7, 0x68, 0x63, 0x0f, 0xf4, 0xbb, 0xe7,
	0x46, 0x61, 0xab, 0xe8, 0x92, 0x3c, 0x6f, 0x46, 0x91, 0x0b, 0xdd, 0xe8, 0x0c, 0x4e, 0xc6, 0x93,
	0x88, 0xad, 0x13, 0xfa, 0xd0, 0x97, 0xcd, 0x4f, 0xf4, 0x01, 0x60, 0xf5, 0xf1, 0x36, 0x67, 0x39,
	0xf9, 0xb9, 0xe3, 0x66, 0x79, 0x8d, 0xd5, 0x8d, 0x98, 0x23, 0x79, 0x06, 0x81, 0x4b, 0x33, 0xd9,
	0x63, 0xbd, 0x60, 0x47, 0x07, 0xcc, 0xbe, 0x02, 0xcc, 0xbd, 0x02, 0xec, 0x75, 0xf3, 0x0a, 0x90,
	0x27, 0x30, 0xb2, 0x61, 0x25, 0xc0, 0xba, 0xd4, 0x6e, 0x62, 0xdb, 0x54, 0x12, 0x60, 0x5d, 0x3c,
	0x37, 0xb1, 0x6d, 0xfe, 0x08, 0xb0, 0x2e, 0x88, 0x7f, 0x65, 0x1f, 0x83, 0x6f, 0xd6, 0x9c, 0x84,
	0xcc, 0x25, 0x2a, 0x02, 0xb6, 0xda, 0xfc, 0xa7, 0x6b, 0x73, 0xdc, 0x5f, 0xbf, 0xff, 0xe8, 0xee,
	0x6f, 0x17, 0xb1, 0xa2, 0x37, 0x6b, 0xdc, 0xd1, 0xdb, 0x7c, 0x74, 0x74, 0xb7, 0xe3, 0xe7, 0xa3,
	0x8f, 0x43, 0xf6, 0xa2, 0x4c, 0x92, 0x91, 0x71, 0x75, 0xf6, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x75,
	0x3f, 0x2a, 0xc7, 0x50, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MemberServiceClient is the client API for MemberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MemberServiceClient interface {
	//註冊
	Registey(ctx context.Context, in *RegisteyReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	//建立帳戶
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	//刪除帳戶
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	//修改帳戶
	Modity(ctx context.Context, in *ModityReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	//登入
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	//獲取用戶清單
	MemberList(ctx context.Context, in *MemberListReq, opts ...grpc.CallOption) (*MemberListResp, error)
	//查詢用戶內容
	MemberInfo(ctx context.Context, in *MemberInfoReq, opts ...grpc.CallOption) (*MemberInfoResp, error)
}

type memberServiceClient struct {
	cc *grpc.ClientConn
}

func NewMemberServiceClient(cc *grpc.ClientConn) MemberServiceClient {
	return &memberServiceClient{cc}
}

func (c *memberServiceClient) Registey(ctx context.Context, in *RegisteyReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/MemberService/Registey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/MemberService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/MemberService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) Modity(ctx context.Context, in *ModityReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/MemberService/Modity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, "/MemberService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) MemberList(ctx context.Context, in *MemberListReq, opts ...grpc.CallOption) (*MemberListResp, error) {
	out := new(MemberListResp)
	err := c.cc.Invoke(ctx, "/MemberService/MemberList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) MemberInfo(ctx context.Context, in *MemberInfoReq, opts ...grpc.CallOption) (*MemberInfoResp, error) {
	out := new(MemberInfoResp)
	err := c.cc.Invoke(ctx, "/MemberService/MemberInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemberServiceServer is the server API for MemberService service.
type MemberServiceServer interface {
	//註冊
	Registey(context.Context, *RegisteyReq) (*emptypb.Empty, error)
	//建立帳戶
	Create(context.Context, *CreateReq) (*emptypb.Empty, error)
	//刪除帳戶
	Delete(context.Context, *DeleteReq) (*emptypb.Empty, error)
	//修改帳戶
	Modity(context.Context, *ModityReq) (*emptypb.Empty, error)
	//登入
	Login(context.Context, *LoginReq) (*LoginResp, error)
	//獲取用戶清單
	MemberList(context.Context, *MemberListReq) (*MemberListResp, error)
	//查詢用戶內容
	MemberInfo(context.Context, *MemberInfoReq) (*MemberInfoResp, error)
}

// UnimplementedMemberServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMemberServiceServer struct {
}

func (*UnimplementedMemberServiceServer) Registey(ctx context.Context, req *RegisteyReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Registey not implemented")
}
func (*UnimplementedMemberServiceServer) Create(ctx context.Context, req *CreateReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedMemberServiceServer) Delete(ctx context.Context, req *DeleteReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedMemberServiceServer) Modity(ctx context.Context, req *ModityReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Modity not implemented")
}
func (*UnimplementedMemberServiceServer) Login(ctx context.Context, req *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedMemberServiceServer) MemberList(ctx context.Context, req *MemberListReq) (*MemberListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MemberList not implemented")
}
func (*UnimplementedMemberServiceServer) MemberInfo(ctx context.Context, req *MemberInfoReq) (*MemberInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MemberInfo not implemented")
}

func RegisterMemberServiceServer(s *grpc.Server, srv MemberServiceServer) {
	s.RegisterService(&_MemberService_serviceDesc, srv)
}

func _MemberService_Registey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisteyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).Registey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MemberService/Registey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).Registey(ctx, req.(*RegisteyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MemberService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).Create(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MemberService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_Modity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).Modity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MemberService/Modity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).Modity(ctx, req.(*ModityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MemberService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_MemberList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).MemberList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MemberService/MemberList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).MemberList(ctx, req.(*MemberListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_MemberInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).MemberInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MemberService/MemberInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).MemberInfo(ctx, req.(*MemberInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MemberService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MemberService",
	HandlerType: (*MemberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Registey",
			Handler:    _MemberService_Registey_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _MemberService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _MemberService_Delete_Handler,
		},
		{
			MethodName: "Modity",
			Handler:    _MemberService_Modity_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _MemberService_Login_Handler,
		},
		{
			MethodName: "MemberList",
			Handler:    _MemberService_MemberList_Handler,
		},
		{
			MethodName: "MemberInfo",
			Handler:    _MemberService_MemberInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "member.proto",
}
